#!/usr/bin/env sh

while IFS=: read k v; do
	if [ -z "$k" ]; then break; fi
	k="$(awk -vk="$k" 'BEGIN { printf "%s",tolower(k) }')"
	v="${v# *}"
	case "$k" in
		"message-id")
			message_id="$(echo "$v" | sed 's/[<>]//g')"
			_message_id="$(echo "$message_id" | sed 's#/#\\/#g')"
			;;
		"from")
			from="$(echo "$v" | sed 's/[<>]//g')"
			;;
		"subject")
			subject="$v"
			;;
	esac
done

exec 0>&-

if [ -z "$message_id" ]; then
	echo "Can't find message-id in message" 1>&2
	exit 1
fi

task_find() {
	if ! task rc.regex:off /"$_message_id"/ "$1" 1>&2; then
		echo "no task found" 1>&2
		return 1
	fi
	return 0
}

task_annotate() {
	if [ "$#" -gt 0 ]; then
		while [ "$#" -gt 0 ]; do
			if [ -n "$1" ]; then
				task "$task_number" status:pending annotate -- "$1"
			fi
			shift
		done
	else
		while true; do
			printf "Annotations? (leave empty if none): " 1>&2
			read annotations 0>&2
			if [ -n "$annotations" ]; then
				task status:pending rc.regex:off /"$_message_id"/ annotate -- "$annotations"
			else
				break
			fi
		done
	fi
}

case "$1" in
	"add")
		printf "task description: " 1>&2
		read description 0>&2
		if [ -n "$description" ] ; then
			task_number="$(task rc.verbose:new-id add -- "$description" | awk -F"[ .]" '$3 ~ /[0-9]+/ { print $3 }')"
			if [ -n "$task_number" ]; then
				task_annotate "$message_id" "$from" "$subject"
			fi
		fi
		;;
	"annotate")
		task_annotate
		;;
	"done")
		echo "Finding task $message_id" 1>&2
		if task_find list; then
			task_annotate
			if ! task status:pending rc.regex:off /"$_message_id"/ "done" 0>&2 1>&2; then
				echo "can't complete task with id $message_id"
			fi
		fi
		exit 1
		;;
	"edit")
		task \( status:pending or status:complete \) /"$_message_id"/ edit 1>&2 0>&2
		;;
	"find")
		task_find all
		exit 1
		;;
	"join")
		task list >&2
		printf "Add this to task #: " >&2
		read task_number 0>&2
		if [ -n "$task_number" ]; then
			task_annotate "$message_id" 1>/dev/null 2>&1
		fi
		;;
	"project")
		printf "Project: "
		read project 0>&2
		if [ -n "$project" ]; then
			if ! task rc.regex:off /"$_message_id"/ modify project:"$project"; then
				echo "Can't change the project for $message_id"
			fi
		fi
		exit 1
		;;
	*)
		;;
esac

exit 0
