#!/usr/bin/env sh

if [ -t 0 ]; then
	printf "task description: " >&2
	read description
	if [ "$description" ] ; then 
		description="$(awk -v d="$description" \
				'BEGIN { gsub(/ /, "\\ ", d); printf "%s", d }')"
		printf "%s" "push <pipe-message>mutt2task\\ '$description'<enter>"
	fi
else
	description="$1"
	task_number="$(task add "$description" 2>/dev/null \
		| awk -F"[ .]" '{ print $3 }')"
	message_id="$(awk -F"[<>]" \
					'tolower($0) ~ /^message-id: / { print $2; exit }')"
	if [ "$message_id" ]; then
		task "$task_number" annotate "$message_id" 1>/dev/null 2>/dev/null
	fi
fi
