#!/usr/bin/env sh

while IFS=: read k v; do
	if [ -z "$k" ]; then break; fi
	k=$(awk -vk="$k" 'BEGIN { printf "%s",tolower(k) }')
	v="${v# *}"
	case "$k" in
		"message-id")
			export message_id="$(echo $v | sed 's/[<>]//g')"
			;;
		"from")
			export from="$(echo $v | sed 's/[<>]//g')"
			;;
		"subject")
			export subject="$v"
			;;
	esac
done

task_find() {
	if ! task description.has:"$message_id" "$1" 1>&2; then
		echo "no task found" 1>&2
		return 1
	fi
	return 0
}

task_annotate() {
	if [ "$#" -gt 0 ]; then
		while [ -n "$1" ]; do
			task "$task_number" status:pending annotate -- "$1"
			shift
		done
	else
		while true; do
			printf "Annotations? (leave empty if none): " 1>&2
			read annotations 0>&2
			if [ "$annotations" ]; then
				task status:pending "$message_id" annotate -- "$annotations"
			else
				break
			fi
		done
	fi
}

case "$1" in
	"add")
		printf "task description: " 1>&2
		read description 0>&2
		if [ "$description" ] ; then
			task_number="$(task add -- "$description" | awk -F"[ .]" '{ print $3 }')"
			if [ "$task_number" ] && [ "$message_id" ]; then
				task_annotate "$message_id" "$from" "$subject"
			fi
		fi
		;;
	"annotate")
		task_annotate
		;;
	"done")
		echo "Finding task $message_id" 1>&2
		if task_find list; then
			task_annotate
			if ! task status:pending description.has:"$message_id" done 0>&2 1>&2; then
				echo "can't complete task with id $message_id"
			fi
		fi
		exit 1
		;;
	"find")
		task_find all
		exit 1
		;;
	"join")
		task list >&2
		printf "Add this to task #: " >&2
		read task_number 0>&2
		if [ "$task_number" ] && [ "$message_id" ]; then
			task_annotate "$message_id" 1>/dev/null 2>&1
		fi
		;;
	"project")
		printf "Project: "
		read project 0>&2
		if [ "$project" ]; then
			if ! task "$message_id" modify project:"$project"; then
				echo "Can't change the project for $message_id"
			fi
		fi
		exit 1
		;;
	*)
		;;
esac

exit 0
